import { MigrationInterface, QueryRunner } from 'typeorm';

export class TypesFixMigration1706804557216 implements MigrationInterface {
  name = 'TypesFixMigration1706804557216';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "diary-template-props" DROP COLUMN "label"`);
    await queryRunner.query(`ALTER TABLE "diary-template-props" ADD "label" character varying(50) NOT NULL`);
    await queryRunner.query(`ALTER TABLE "workouts" DROP COLUMN "name"`);
    await queryRunner.query(`ALTER TABLE "workouts" ADD "name" character varying(50) NOT NULL`);
    await queryRunner.query(`ALTER TABLE "workouts" DROP COLUMN "comment"`);
    await queryRunner.query(`ALTER TABLE "workouts" ADD "comment" character varying(250)`);
    await queryRunner.query(`ALTER TABLE "exercises" DROP COLUMN "name"`);
    await queryRunner.query(`ALTER TABLE "exercises" ADD "name" character varying(100) NOT NULL`);
    await queryRunner.query(`ALTER TABLE "exercises" DROP COLUMN "trainerComment"`);
    await queryRunner.query(`ALTER TABLE "exercises" ADD "trainerComment" character varying(250)`);
    await queryRunner.query(`ALTER TABLE "exercises" DROP COLUMN "weight"`);
    await queryRunner.query(`ALTER TABLE "exercises" ADD "weight" double precision NOT NULL`);
    await queryRunner.query(`ALTER TABLE "exercises" DROP COLUMN "repetitions"`);
    await queryRunner.query(`ALTER TABLE "exercises" ADD "repetitions" character varying(50) NOT NULL`);
    await queryRunner.query(`ALTER TABLE "exercises" DROP COLUMN "pace"`);
    await queryRunner.query(`ALTER TABLE "exercises" ADD "pace" character varying(50) NOT NULL`);
    await queryRunner.query(`ALTER TABLE "exercises" DROP COLUMN "photoLink"`);
    await queryRunner.query(`ALTER TABLE "exercises" ADD "photoLink" character varying(250) NOT NULL`);
    await queryRunner.query(`ALTER TABLE "exercises" DROP COLUMN "videoLink"`);
    await queryRunner.query(`ALTER TABLE "exercises" ADD "videoLink" character varying(250) NOT NULL`);
    await queryRunner.query(`ALTER TABLE "files" DROP COLUMN "fileName"`);
    await queryRunner.query(`ALTER TABLE "files" ADD "fileName" character varying(50) NOT NULL`);
    await queryRunner.query(`ALTER TABLE "files" DROP COLUMN "path"`);
    await queryRunner.query(`ALTER TABLE "files" ADD "path" character varying(250) NOT NULL`);
    await queryRunner.query(`ALTER TABLE "files" DROP COLUMN "fileLInk"`);
    await queryRunner.query(`ALTER TABLE "files" ADD "fileLInk" character varying(250) NOT NULL`);
    await queryRunner.query(`ALTER TABLE "diary-props" DROP COLUMN "label"`);
    await queryRunner.query(`ALTER TABLE "diary-props" ADD "label" character varying(50) NOT NULL`);
    await queryRunner.query(`ALTER TABLE "diaries" DROP COLUMN "behaviour"`);
    await queryRunner.query(`ALTER TABLE "diaries" ADD "behaviour" character varying(50) NOT NULL`);
    await queryRunner.query(`ALTER TABLE "diaries" ALTER COLUMN "sum" DROP NOT NULL`);
    await queryRunner.query(`ALTER TABLE "diaries" DROP COLUMN "activity"`);
    await queryRunner.query(`ALTER TABLE "diaries" ADD "activity" character varying(250)`);
    await queryRunner.query(`ALTER TABLE "diaries" ALTER COLUMN "steps" DROP NOT NULL`);
    await queryRunner.query(`ALTER TABLE "nutrition" DROP COLUMN "name"`);
    await queryRunner.query(`ALTER TABLE "nutrition" ADD "name" character varying(50) NOT NULL`);
    await queryRunner.query(`ALTER TABLE "meal-items" DROP COLUMN "type"`);
    await queryRunner.query(`ALTER TABLE "meal-items" ADD "type" character varying(50) NOT NULL`);
    await queryRunner.query(`ALTER TABLE "meal-items" DROP COLUMN "quantity"`);
    await queryRunner.query(`ALTER TABLE "meal-items" ADD "quantity" character varying(50) NOT NULL`);
    await queryRunner.query(`ALTER TABLE "food" DROP COLUMN "type"`);
    await queryRunner.query(`ALTER TABLE "food" ADD "type" character varying(50) NOT NULL`);
    await queryRunner.query(`ALTER TABLE "food" DROP COLUMN "name"`);
    await queryRunner.query(`ALTER TABLE "food" ADD "name" character varying(50) NOT NULL`);
    await queryRunner.query(`ALTER TABLE "prompts" DROP COLUMN "type"`);
    await queryRunner.query(`ALTER TABLE "prompts" ADD "type" character varying(50) NOT NULL`);
    await queryRunner.query(`ALTER TABLE "prompts" DROP COLUMN "photoLink"`);
    await queryRunner.query(`ALTER TABLE "prompts" ADD "photoLink" character varying(250) NOT NULL`);
    await queryRunner.query(`ALTER TABLE "prompts" DROP COLUMN "videoLink"`);
    await queryRunner.query(`ALTER TABLE "prompts" ADD "videoLink" character varying(250) NOT NULL`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "prompts" DROP COLUMN "videoLink"`);
    await queryRunner.query(`ALTER TABLE "prompts" ADD "videoLink" character varying NOT NULL`);
    await queryRunner.query(`ALTER TABLE "prompts" DROP COLUMN "photoLink"`);
    await queryRunner.query(`ALTER TABLE "prompts" ADD "photoLink" character varying NOT NULL`);
    await queryRunner.query(`ALTER TABLE "prompts" DROP COLUMN "type"`);
    await queryRunner.query(`ALTER TABLE "prompts" ADD "type" character varying NOT NULL`);
    await queryRunner.query(`ALTER TABLE "food" DROP COLUMN "name"`);
    await queryRunner.query(`ALTER TABLE "food" ADD "name" character varying NOT NULL`);
    await queryRunner.query(`ALTER TABLE "food" DROP COLUMN "type"`);
    await queryRunner.query(`ALTER TABLE "food" ADD "type" character varying NOT NULL`);
    await queryRunner.query(`ALTER TABLE "meal-items" DROP COLUMN "quantity"`);
    await queryRunner.query(`ALTER TABLE "meal-items" ADD "quantity" character varying NOT NULL`);
    await queryRunner.query(`ALTER TABLE "meal-items" DROP COLUMN "type"`);
    await queryRunner.query(`ALTER TABLE "meal-items" ADD "type" character varying NOT NULL`);
    await queryRunner.query(`ALTER TABLE "nutrition" DROP COLUMN "name"`);
    await queryRunner.query(`ALTER TABLE "nutrition" ADD "name" character varying NOT NULL`);
    await queryRunner.query(`ALTER TABLE "diaries" ALTER COLUMN "steps"`);
    await queryRunner.query(`ALTER TABLE "diaries" DROP COLUMN "activity"`);
    await queryRunner.query(`ALTER TABLE "diaries" ADD "activity" character varying`);
    await queryRunner.query(`ALTER TABLE "diaries" ALTER COLUMN "sum"`);
    await queryRunner.query(`ALTER TABLE "diaries" DROP COLUMN "behaviour"`);
    await queryRunner.query(`ALTER TABLE "diaries" ADD "behaviour" character varying NOT NULL`);
    await queryRunner.query(`ALTER TABLE "diary-props" DROP COLUMN "label"`);
    await queryRunner.query(`ALTER TABLE "diary-props" ADD "label" character varying NOT NULL`);
    await queryRunner.query(`ALTER TABLE "files" DROP COLUMN "fileLInk"`);
    await queryRunner.query(`ALTER TABLE "files" ADD "fileLInk" character varying NOT NULL`);
    await queryRunner.query(`ALTER TABLE "files" DROP COLUMN "path"`);
    await queryRunner.query(`ALTER TABLE "files" ADD "path" character varying NOT NULL`);
    await queryRunner.query(`ALTER TABLE "files" DROP COLUMN "fileName"`);
    await queryRunner.query(`ALTER TABLE "files" ADD "fileName" character varying NOT NULL`);
    await queryRunner.query(`ALTER TABLE "exercises" DROP COLUMN "videoLink"`);
    await queryRunner.query(`ALTER TABLE "exercises" ADD "videoLink" character varying NOT NULL`);
    await queryRunner.query(`ALTER TABLE "exercises" DROP COLUMN "photoLink"`);
    await queryRunner.query(`ALTER TABLE "exercises" ADD "photoLink" character varying NOT NULL`);
    await queryRunner.query(`ALTER TABLE "exercises" DROP COLUMN "pace"`);
    await queryRunner.query(`ALTER TABLE "exercises" ADD "pace" character varying NOT NULL`);
    await queryRunner.query(`ALTER TABLE "exercises" DROP COLUMN "repetitions"`);
    await queryRunner.query(`ALTER TABLE "exercises" ADD "repetitions" character varying NOT NULL`);
    await queryRunner.query(`ALTER TABLE "exercises" DROP COLUMN "weight"`);
    await queryRunner.query(`ALTER TABLE "exercises" ADD "weight" integer NOT NULL`);
    await queryRunner.query(`ALTER TABLE "exercises" DROP COLUMN "trainerComment"`);
    await queryRunner.query(`ALTER TABLE "exercises" ADD "trainerComment" character varying`);
    await queryRunner.query(`ALTER TABLE "exercises" DROP COLUMN "name"`);
    await queryRunner.query(`ALTER TABLE "exercises" ADD "name" character varying NOT NULL`);
    await queryRunner.query(`ALTER TABLE "workouts" DROP COLUMN "comment"`);
    await queryRunner.query(`ALTER TABLE "workouts" ADD "comment" character varying`);
    await queryRunner.query(`ALTER TABLE "workouts" DROP COLUMN "name"`);
    await queryRunner.query(`ALTER TABLE "workouts" ADD "name" character varying NOT NULL`);
    await queryRunner.query(`ALTER TABLE "diary-template-props" DROP COLUMN "label"`);
    await queryRunner.query(`ALTER TABLE "diary-template-props" ADD "label" character varying NOT NULL`);
  }
}
