FROM node:16 as installer
WORKDIR /app
COPY ./package.json ./package.json
COPY ./yarn.lock ./yarn.lock
COPY ./tsconfig.json ./tsconfig.json
COPY ./back-body-blast ./back-body-blast

FROM node:16 as builder
WORKDIR /app
COPY --from=installer /app .
RUN yarn install --frozen-lockfile
RUN yarn workspace back-body-blast build
RUN yarn install --production --ignore-scripts --prefer-offline --frozen-lockfile

FROM node:16 as runner
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
CMD ["node", "dist/back-body-blast/src/main.js"]